# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    # General
        # Up to 10 MiB cause emoji font
    -   id: check-added-large-files
        args: ['--maxkb=10240']
    -   id: fix-byte-order-marker
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
        args: ['./scripts/versionate', './scripts/update_gallery']
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    # Python 3.9 codebase
    -   id: check-ast
    -   id: debug-statements
    -   id: fix-encoding-pragma
        args: ['--remove']
    -   id: check-docstring-first
    # Git
    -   id: no-commit-to-branch
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
