#!/usr/bin/env python3
import os
import shutil
import argparse
from pathlib import Path

ARCHIVED = Path("./archived/")

def parse_args():
    parser = argparse.ArgumentParser()

    parser.description = (
        f"""Get out of my way! I don't want to deal with you!
        Move files into {ARCHIVED}"""
    )

    parser.add_argument("targets", nargs="+", help="files to move")

    parser.add_argument(
        "--dry",
        "-d",
        action="store_true",
        help="Dry run.",
    )

    return parser.parse_args()


if __name__ == "__main__":

    args = parse_args()

    DRY = args.dry
    TARGETS = args.targets

    try:
        if DRY:
            print(f"os.mkdir({ARCHIVED})")
        else:
            os.mkdir(ARCHIVED)
    except FileExistsError:
        if ARCHIVED.is_file():
            sys.exit(f"Error: {path} is a file.")


    for target in TARGETS:
        target = Path(target)
        if target == ARCHIVED: continue
        if DRY:
            print(f"shutil.move({target}, {ARCHIVED})")
        else:
            shutil.move(target, ARCHIVED)
