#!/usr/bin/env python

import argparse
import datetime as dt
import os
import re
import shutil
import sys
from pathlib import Path

# Doing the small stuff first
# Leave the high level for later

# Defaults
ARCHIVE_DIR = r"archived"
EXCLUDE_REGEX = r"^EM|^em_"

parser = argparse.ArgumentParser()

parser.description = (
    "Get out of the way!!! Moves unmarked files into the 'archived' directory."
)

parser.add_argument(
    "description", nargs="?", default="", help="It will be appended to the archiving directory."
)

# parser.add_argument(
#     "archive_dir", nargs="?", help="It will be appended to the archiving directory."
# )

# parser.add_argument(
#     "description", nargs="?", help="It will be appended to the archiving directory."
# )


parser.add_argument(
    "--dry",
    "-d",
    action="store_true",
    help="Dry run.",
)

args = parser.parse_args()


SUFFIX = args.description
# DRY = args.dry
DRY = args.dry

# print(f"Suffix is {suffix}")


def generate_name(suffix: str = ""):
    NOW = dt.datetime.now()
    iso_date = NOW.strftime("%F")  # ISO date
    week_day = NOW.strftime(".%V-%u")  # Week 1..53, and Day 1..7 starting on Monday
    return iso_date + week_day + suffix


def get_targets():

    dot_files = r"^\.|"
    archive_dir = r"^" + ARCHIVE_DIR + r"$|"
    regex = dot_files + archive_dir + EXCLUDE_REGEX

    RE_EXCLUDE = re.compile(rf"{regex}")

    return [i for i in os.listdir() if not re.search(RE_EXCLUDE, i)]


def check_create(path):
    path = Path(path)
    if not os.path.exists(path):
        os.makedirs(path)
    else:
        if path.is_file():
            sys.exit(f"Error: {path} is a file, doing NOTHING")


if __name__ == "__main__":

    BASE = "archived/"
    DAY = generate_name(SUFFIX)
    DESTINATION = BASE + DAY

    if DRY: print(f"Dry Run: {DESTINATION} would've been created")

    check_create(DESTINATION)

    TARGETS = get_targets()
    if DRY: print(f"Dry Run: {TARGETS} would've moved.")

    if not DRY:
        for target in TARGETS:
            shutil.move(target, DESTINATION)
